//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog_Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Level
    {
        public int id { get; set; }
        public Nullable<int> Parent_id { get; set; }
        public string Name { get; set; }
    }
}
