//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalog_Test
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ETSGroupEntities : DbContext
    {
        public ETSGroupEntities()
            : base("name=ETSGroupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aggregate> Aggregate { get; set; }
        public virtual DbSet<Catalog> Catalog { get; set; }
        public virtual DbSet<Catalog_Level> Catalog_Level { get; set; }
        public virtual DbSet<Model> Model { get; set; }
    }
}
